stages:
  get_data:
    cmd: python get_data.py
    deps:
      - get_data.py
    outs:
      - ../../artifacts/f1/data/raw/circuits.csv
      - ../../artifacts/f1/data/raw/constructor_results.csv
      - ../../artifacts/f1/data/raw/constructors.csv
      - ../../artifacts/f1/data/raw/lap_times.csv
      - ../../artifacts/f1/data/raw/pit_stops.csv
      - ../../artifacts/f1/data/raw/qualifying.csv
      - ../../artifacts/f1/data/raw/races.csv
      - ../../artifacts/f1/data/raw/results.csv
      - ../../artifacts/f1/data/raw/seasons.csv
      - ../../artifacts/f1/data/raw/driver_standings.csv
      - ../../artifacts/f1/data/raw/constructor_standings.csv
      - ../../artifacts/f1/data/raw/drivers.csv
      - ../../artifacts/f1/data/raw/status.csv
      - ../../artifacts/f1/data/raw/sprint_results.csv

  prepare:
    cmd: python prepare_data.py
    deps:
      - prepare_data.py
      - ../../artifacts/f1/data/raw/circuits.csv
      - ../../artifacts/f1/data/raw/constructor_results.csv
      - ../../artifacts/f1/data/raw/constructors.csv
      - ../../artifacts/f1/data/raw/qualifying.csv
      - ../../artifacts/f1/data/raw/races.csv
      - ../../artifacts/f1/data/raw/results.csv
      - ../../artifacts/f1/data/raw/drivers.csv
    outs:
      - ../../artifacts/f1/data/prepared/prepared_data.csv
  
  feature_engineering:
    cmd: python feature_engineering.py
    deps:
      - feature_engineering.py
      - ../../artifacts/f1/data/prepared/prepared_data.csv
    outs:
      - ../../artifacts/f1/data/featured/train.csv
      - ../../artifacts/f1/data/featured/valid.csv
      - ../../artifacts/f1/data/featured/test.csv
    
  train:
    cmd: python train_model.py
    deps:
      - train_model.py
      - ../../artifacts/f1/data/featured/train.csv
      - ../../artifacts/f1/data/featured/valid.csv
    outs:
      - ../../artifacts/f1/models/model.pkl