stages:
  get_data:
    cmd: python get_data.py
    deps:
    - get_data.py
    outs:
    - ../../data/ca_house_prediction/housing.csv

  prepare:
    cmd: python prepare_data.py
    deps:
    - prepare_data.py
    - ../../data/ca_house_prediction/housing.csv
    outs:
    - ../../data/ca_house_prediction/X_train.csv
    - ../../data/ca_house_prediction/X_test.csv
    - ../../data/ca_house_prediction/y_train.csv
    - ../../data/ca_house_prediction/y_test.csv

  train:
    cmd: python train_model.py
    deps:
    - train_model.py
    - ../../data/ca_house_prediction/X_train.csv
    - ../../data/ca_house_prediction/y_train.csv
    outs:
    - ../../models/ca_house_prediction/model.pkl